### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by Jey-Cee** [Mic-M/iobroker-createUserStates#2]
Hi Mic-M,

kannst du das Repo umbennen, der Name den du verwendest suggeriert das es sich um einen Adapter handelt.

Gruß Jey Cee

**Comment by Mic-M** [comment]
Hi Jey Cee,

danke für deine Meldung. Mein "Problem" ist, dass ich damals einige JavaScripts in der Syntax "iobroker.Titel" angelegt habe, weil ich dachte "das gehört sich so", und so auch von anderen Usern auf Github sah.
Wenn ich die jetzt alle umbenenne, führen wohl alle bestehenden Links im Forum und der User-Bookmarks ins Leere (404).

Wäre es akzeptabel, jeweils in der Readme einen fetten Hinweis gleich am Anfang, dass es sich hier nicht um Adapter handelt?

Auszug:
![image](https://user-images.githubusercontent.com/39859059/91066188-b30d4a00-e631-11ea-902d-6d5066fef2dc.png)

Grüße
Mic

**Comment by Jey-Cee** [comment]
Nein weil es Automatische tools gibt die jedes repo mit dieser art von Bennung durchgehen. Das ist viel unnützer traffic, github blockiert dann irgendwann und man muss das etappen weise machen.

**Comment by Mic-M** [comment]
ok, verstehe. Was wäre denn ein Vorschlag als Namensgebung für ioBroker-related Scripts? <ioBroker-Titel>, also minus als Trenner, ioBroker groß oder klein?

**Comment by Jey-Cee** [comment]
Minus als trenner passt. Der rest, groß/klein schreibung ist dann egal.

**Comment by Mic-M** [comment]
hab jetzt alle umbenannt.

**Comment by Jey-Cee** [comment]
Danke
